[params.homeInfoParams]
    Title = "Hi there, I'm JBG ğŸ‘‹"
    Content = "ëŠì„ì—†ì´ ì„±ì¥í•˜ëŠ” í’€ìŠ¤íƒ ê°œë°œìì˜ ê¸°ìˆ  ì•„ì¹´ì´ë¸Œì…ë‹ˆë‹¤."

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/bonggyunjo"
[[params.socialIcons]]
    name = "velog" # velog ì•„ì´ì½˜ì´ ì§€ì› ì•ˆ ë  ê²½ìš° "blog" ì¶”ì²œ
    url = "https://velog.io/@jbong"
[[params.socialIcons]]
    name = "email"
    url = "mailto:kjbg4565388@gmail.com"

[params.profileMode]
    enabled = true # í”„ë¡œí•„ ëª¨ë“œ í™œì„±í™”
    title = "JBG Tech Archive"
    subtitle = "ì‹œí–‰ì°©ì˜¤ë¥¼ í†µí•´ ì–»ì€ ê¸°ìˆ ì  ì¸ì‚¬ì´íŠ¸ë¥¼ ê¸°ë¡í•©ë‹ˆë‹¤."
    imageUrl = "img/profile.jpg" # í”„ë¡œí•„ ì´ë¯¸ì§€ ê²½ë¡œ
    imageWidth = 150
    imageHeight = 150
    
    [[params.profileMode.buttons]]
        name = "Posts"
        url = "posts"
    [[params.profileMode.buttons]]
        name = "Tags"
        url = "tags"